name: Check Markdown links

on:
  push:
    branches: [main]
  pull_request:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          use-verbose-mode: "yes"
          use-quiet-mode: "yes"
          config-file: ".github/workflows/url-check-config.json"
          check-modified-files-only: "yes"
          base-branch: "main"
