name: Check Markdown links Periodically

on:
  schedule:
    # Run everyday at 0:00 AM
    - cron: "0 0 * * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          use-verbose-mode: "yes"
          use-quiet-mode: "yes"
          config-file: ".github/workflows/url-check-config.json"
          base-branch: "main"
